module.exports = {
  RECEIVE_AMBASSADORS: "RECEIVE_AMBASSADORS",
  RECEIVE_BOOKED_AMBASSADORS: "RECEIVE_BOOKED_AMBASSADORS",
  BOOK_AMBASSADOR: "BOOK_AMBASSADOR",
  REMOVE_AMBASSADOR: "REMOVE_AMBASSADOR",
  HOVER_BOOK_AMBASSADOR: "HOVER_BOOK_AMBASSADOR",
  FILTER_OUT_AMBASSADOR: "FILTER_OUT_AMBASSADOR",
  ROLE_SELECTED_AMBASSADORS:"ROLE_SELECTED_AMBASSADORS"
}
