module.exports = {
  RECEIVE_LOCATION: "RECEIVE_LOCATION",
  RECEIVE_LOCATIONS: "RECEIVE_LOCATIONS",
  SET_LOCATION: "SET_LOCATION",
  RECEIVE_EDIT_LOCATION: "RECEIVE_EDIT_LOCATION",
  RECEIVE_DELETE_LOCATION: "RECEIVE_DELETE_LOCATION"
}
