module.exports = {
  RECEIVE_ROLE_TYPES: "RECEIVE_ROLE_TYPES",
  SELECT_ROLE:"SELECT_ROLE",
  ADD_ROLE:"ADD_ROLE",
  CLEAR_ADDED_ROLE:"CLEAR_ADDED_ROLE",
  ADD_ROLE_POPUP:"ADD_ROLE_POPUP",
  REMOVE_ROLE_POPUP:"REMOVE_ROLE_POPUP"
}
